### ISSUE TITLE
프로젝트 정보 수정 (인원 수정 제외)

### ISSUE THREAD

**Issue by jjanddak** [codestates/Todo.gg_Server#40]
### ISSUE
- Type: `bug`, `feature`

### TODO
- [x] 프로젝트 제목 수정 
- [x] 프로젝트 설명 수정
- [x] start_date, end_date 수정 (둘중 하나만 할수도 있다)
